steps:
 - name: maven:3-jdk-8
   entrypoint: mvn
   args: ['package','-Dmaven.test.skip=true']
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/saumabha/helloworld-boot-docker:$COMMIT_SHA', '.']
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/saumabha/helloworld-boot-docker:$COMMIT_SHA']
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   args: ['run', 'deploy', 'cloudrun-demo', '--image', 'gcr.io/saumabha/helloworld-boot-docker:$COMMIT_SHA', '--region', 'us-central1', '--platform', 'managed']
 images:
 - gcr.io/saumabha/helloworld-boot-docker:$COMMIT_SHA       