steps:
 - name: maven:3-jdk-8
   entrypoint: mvn
   args: ['package','-Dmaven.test.skip=true']
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'eu.gcr.io/saumabha/helloworld-boot-docker:v3', '--build-arg=JAR_FILE=target/Hello-World-0.0.1-SNAPSHOT.jar', '.']
 images: ['eu.gcr.io/saumabha/helloworld-boot-docker:v3'] 
