steps:
 - name: maven:3-jdk-8
   entrypoint: mvn
   args: ['package','-Dmaven.test.skip=true']
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'eu.gcr.io/saumabha/helloworld-boot-docker:v3', '.']
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', ' eu.gcr.io/saumabha/helloworld-boot-docker:v3']   