steps:
 - name: 'eu.gcr.io/saumabha/helloworld-boot-docker'
   args: ['build', '-t', 'eu.gcr.io/saumabha/helloworld-boot-docker:$COMMIT_SHA', '.']
 - name: 'eu.gcr.io/saumabha/helloworld-boot-docker'
   args: ['push', ' eu.gcr.io/saumabha/helloworld-boot-docker:$COMMIT_SHA']    
