steps:
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'eu.gcr.io/saumabha/helloworld-boot-docker:v2', '.']
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', ' eu.gcr.io/saumabha/helloworld-boot-docker:v2']    
